services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-server
    privileged: true
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gestion-network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-server
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - gestion-network

volumes:
  jenkins_home:
  n8n_data:

networks:
  gestion-network:
    external: true